### ISSUE TITLE
docker compose 中权限问题

### ISSUE THREAD

**Issue by WizardMeow** [ChisBread/qbittorrent_skip_patch#1]
下载库文件权限如
```
drwxr-x--- 4 user media      4.0K 1月  23 16:47
```

docker compose file sample
```
qbittorrent:
    image: chisbread/qbittorrent
    user: 1000:1001 # 注意这个选项
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-torrents:/torrents
      - /mnt/media/pt/downloads:/downloads
      - /mnt/media/pt:/mnt/pt
    ports:
      - 31030:8080
      - 31031:6881/tcp
      - 31031:6881/udp
    restart: unless-stopped
```

如果不加上user选项，会导致qb写出文件都是root:root，与媒体库权限冲突
如果加上user，qb会无法创建需要的配置文件，导致无法启动

希望如https://hub.docker.com/r/linuxserver/qbittorrent
提供PUID/PGID
